version: "3"

services:
  app:
    build:
      context: ./app
    container_name: strapi-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: blog_db
      DATABASE_USERNAME: asad_blog
      DATABASE_PASSWORD: asad_blog
    volumes:
      - ./app:/srv/app
    ports:
      - 127.0.0.1:1337:1337
    depends_on:
      - db

  db:
    ports:
      - 5432:5432
    image: postgres:13
    container_name: strapi-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: asad_blog
      POSTGRES_PASSWORD: asad_blog
    volumes:
      - ./data:/var/lib/postgresql/data
